/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.Person;
import model.PersonDirectory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author shshyam
 */
public class CommunityViewPersons extends javax.swing.JPanel {

    /**
     * Creates new form CommunityViewPersons
     */
    
    PersonDirectory persondirectory;
    int HealthyCount;
    int UnhealthyCount;
   
    CommunityViewPersons(PersonDirectory persondirectory) {
        initComponents();
        
        this.persondirectory=persondirectory;
        populateTableAll(persondirectory.getPersonHistory());
        
       
       
      
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private void populateTable(ArrayList<Person> persondirectory,String community) {
          
        DefaultTableModel dtm1 = (DefaultTableModel) tblHealthyPeople.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) tblUnhealthyPeople.getModel();
        dtm1.setRowCount(0);
        dtm2.setRowCount(0);
        int healthy=0;
        int unhealthy=0;
        
        for(Person person: persondirectory){
           // Patient patient=person.getPatient();
            if(person.getCommunity().equals(community))
            {
            Object[] row = new Object[4];
            row[0] = person;
            row[1]= String.valueOf(person.getAge());
            row[2]= person.getAddress();
            row[3]= person.getCommunity();
            
            if("Normal".equals(person.getHealth().trim()))
            {dtm1.addRow(row);
            healthy++;
            }
            
            else
            {
             dtm2.addRow(row);
             unhealthy++;       
            }
            }}
        
        txtHealthyCounts.setText(String.valueOf(healthy));
        txtUnhealthyCounts.setText(String.valueOf(unhealthy));
        this.HealthyCount=healthy;
        this.UnhealthyCount=unhealthy;
      }
       
private void populateTableAll(ArrayList<Person> persondirectory) {
          
        DefaultTableModel dtm1 = (DefaultTableModel) tblHealthyPeople.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) tblUnhealthyPeople.getModel();
        dtm1.setRowCount(0);
        dtm2.setRowCount(0);
        int healthy=0;
        int unhealthy=0;
        
        for(Person person: persondirectory){
            
            Object[] row = new Object[4];
            row[0] = person;
            row[1]= String.valueOf(person.getAge());
            row[2]= person.getAddress();
            row[3]= person.getCommunity();
            
            if("Normal".equals(person.getHealth()))
            {dtm1.addRow(row);
            healthy++;
            }
            
            else
            {
             dtm2.addRow(row);
             unhealthy++;       
            }
            }
        
        txtHealthyCounts.setText(String.valueOf(healthy));
        txtUnhealthyCounts.setText(String.valueOf(unhealthy));
        this.HealthyCount=healthy;
        this.UnhealthyCount=unhealthy;
        
      }
     
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHealthyPeople = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUnhealthyPeople = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUnhealthyCounts = new javax.swing.JTextField();
        txtHealthyCounts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        btnViewCommunity = new javax.swing.JButton();
        btnViewChart = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel2.setBackground(new java.awt.Color(62, 193, 211));

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Community View");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel2)
                .addGap(349, 349, 349))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tblHealthyPeople.setFont(new java.awt.Font("Optima", 0, 10)); // NOI18N
        tblHealthyPeople.setForeground(new java.awt.Color(0, 102, 102));
        tblHealthyPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHealthyPeople.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblHealthyPeople);
        tblHealthyPeople.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        tblUnhealthyPeople.setFont(new java.awt.Font("Optima", 0, 10)); // NOI18N
        tblUnhealthyPeople.setForeground(new java.awt.Color(0, 102, 102));
        tblUnhealthyPeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUnhealthyPeople);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 178, 202));
        jLabel1.setText("Unhealthy Community Members");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 178, 202));
        jLabel3.setText("Type Community to view data for");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Total Healthy Members");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Total Unhealthy members");

        txtUnhealthyCounts.setEditable(false);
        txtUnhealthyCounts.setBackground(new java.awt.Color(204, 204, 204));
        txtUnhealthyCounts.setCaretColor(new java.awt.Color(51, 153, 0));

        txtHealthyCounts.setEditable(false);
        txtHealthyCounts.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 178, 202));
        jLabel6.setText("Healthy Community Members");

        txtCommunity.setBackground(new java.awt.Color(204, 204, 204));
        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        btnViewCommunity.setBackground(new java.awt.Color(255, 255, 255));
        btnViewCommunity.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        btnViewCommunity.setForeground(new java.awt.Color(0, 178, 202));
        btnViewCommunity.setText("View");
        btnViewCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunityActionPerformed(evt);
            }
        });

        btnViewChart.setBackground(new java.awt.Color(255, 255, 255));
        btnViewChart.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        btnViewChart.setForeground(new java.awt.Color(0, 178, 202));
        btnViewChart.setText("Visualize Trends");
        btnViewChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel6)
                .addGap(184, 184, 184)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCommunity)
                    .addComponent(jLabel1))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(txtHealthyCounts, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(txtUnhealthyCounts, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(379, 379, 379))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewChart, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCommunity))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnhealthyCounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthyCounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewChart)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void btnViewCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunityActionPerformed
        // TODO add your handling code here:
        int flag=0;
        for(Person person: this.persondirectory.getPersonHistory()){
             if(txtCommunity.getText().equals(person.getCommunity().trim()))
             {
                 flag=1;
             }
        }
         if(flag==0)    
           {
            JOptionPane.showMessageDialog(this,"No Community found with the given name! Try again!");
            return;
        }
         else
         populateTable(persondirectory.getPersonHistory(),txtCommunity.getText());
                 
        
        
    }//GEN-LAST:event_btnViewCommunityActionPerformed

    private void btnViewChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChartActionPerformed
       DefaultPieDataset pieDataSet = new DefaultPieDataset();
       pieDataSet.setValue("Normal Vital Signs",HealthyCount);
       pieDataSet.setValue("Abnormal Vital Signs",UnhealthyCount);

       
       JFreeChart piechart = ChartFactory.createPieChart("Health Trends of Community",pieDataSet,true,true,true);
       PiePlot P=(PiePlot)piechart.getPlot();
       //P.setForegroundAlpha(TOP_ALIGNMENT);
       ChartFrame frame = new ChartFrame("Health Trends",piechart);
       frame.setVisible(true);
       frame.setSize(450,500);
       
    }//GEN-LAST:event_btnViewChartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewChart;
    private javax.swing.JButton btnViewCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHealthyPeople;
    private javax.swing.JTable tblUnhealthyPeople;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHealthyCounts;
    private javax.swing.JTextField txtUnhealthyCounts;
    // End of variables declaration//GEN-END:variables
}
