/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shshyam
 */
public class CommunityAddPersons extends javax.swing.JPanel {
    PersonDirectory persondirectory;
    /**
     * Creates new form AdminAddInventory
     */
    public CommunityAddPersons(PersonDirectory persondirectory) {
        initComponents();
        this.persondirectory=persondirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCarSerNum = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCarNumPlate = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblMaintExpDate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnAddSample = new javax.swing.JButton();
        comboAge = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel2.setBackground(new java.awt.Color(62, 193, 211));

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Person Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );

        lblCarSerNum.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarSerNum.setForeground(new java.awt.Color(0, 102, 102));
        lblCarSerNum.setText("Name                                                      :");

        txtName.setBackground(new java.awt.Color(204, 204, 204));

        lblCarNumPlate.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarNumPlate.setForeground(new java.awt.Color(0, 102, 102));
        lblCarNumPlate.setText("House Address                                         :");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));

        lblModel.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(0, 102, 102));
        lblModel.setText("Community                                             :");

        txtCommunity.setBackground(new java.awt.Color(204, 204, 204));

        lblCity.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setText("City                                                         :");

        txtCity.setBackground(new java.awt.Color(204, 204, 204));

        lblMaintExpDate.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblMaintExpDate.setForeground(new java.awt.Color(0, 102, 102));
        lblMaintExpDate.setText("Age                                                         :");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 178, 202));
        btnSave.setText("Save Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAddSample.setBackground(new java.awt.Color(255, 255, 255));
        btnAddSample.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnAddSample.setForeground(new java.awt.Color(0, 178, 202));
        btnAddSample.setText("Add Sample Data");
        btnAddSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSampleActionPerformed(evt);
            }
        });

        comboAge.setBackground(new java.awt.Color(204, 204, 204));
        comboAge.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        comboAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        comboAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSample, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(333, 333, 333))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarSerNum)
                            .addComponent(lblCarNumPlate)
                            .addComponent(lblModel)
                            .addComponent(lblCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCommunity))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMaintExpDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAge, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddSample, btnSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarNumPlate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintExpDate)
                    .addComponent(comboAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAddSample, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        //Validations for fields below:
        
        int failsafe=0;
         if(txtName.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Name must not be Empty!");
               failsafe=1;
         }
         
      for (Person personiterator : this.persondirectory.getPersonHistory())
        {
           if( personiterator.getName().equals(txtName.getText().isEmpty()?"":txtName.getText()))
           {
               JOptionPane.showMessageDialog(this, "Person details already exist! Please choose update details");
               failsafe=1;
           } 
        }
         
              if(txtAddress.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Address must not be Empty!");
               failsafe=1;
         }
         
                  if(txtCommunity.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Community must not be Empty!");
               failsafe=1;
         }
        
              
          if(txtCity.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "City must not be Empty!");
               failsafe=1;
         }
      
        

          
        if(failsafe==0)
        {
            
        Person person = persondirectory.createAndAddPerson();
        person.setName(txtName.getText());
        person.setAge(Integer.valueOf(comboAge.getSelectedItem().toString()));
        person.setCommunity(txtCommunity.getText());
        person.setCity(txtCity.getText());
        person.setAddress(txtAddress.getText());
  SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
        person.setUpdateDate(formatter.format(new Date()));
        JOptionPane.showMessageDialog(this, "Details saved successfully!");
       }
            
        
        txtName.setText("");
        txtCity.setText("");
        txtCommunity.setText("");
        txtAddress.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSampleActionPerformed
        // TODO add your handling code here:
      File file = new File("src/Resources/SampleData.txt");

         try {
            Scanner sc = new Scanner(file);
             SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
            while (sc.hasNextLine()) {
                String readLine = sc.nextLine();
                String[] lineArray = readLine.split(",");
                
                Person v = this.persondirectory.createAndAddPerson();
                v.setName(lineArray[0].trim());
                v.setAddress(lineArray[1].trim());
                v.setCommunity(lineArray[2].trim());  
                v.setCity(lineArray[3].trim());
                v.setAge(Integer.valueOf(lineArray[4].trim()));
                v.setUpdateDate(formatter.format(new Date()));
            }

        JOptionPane.showMessageDialog(this, "Sample Data Added successfully!");
            
            sc.close();
         } catch(Exception e) {
             e.printStackTrace();
         }
        
    }//GEN-LAST:event_btnAddSampleActionPerformed

    private void comboAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSample;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboAge;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCarNumPlate;
    private javax.swing.JLabel lblCarSerNum;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintExpDate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
