/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author shshyam
 */
public class CommunityUpdatePersons extends javax.swing.JPanel {
    PersonDirectory persondirectory;
    //private Object txtMostRecentUpdate;
    /**
     * Creates new form AdminUpdateInventory
     */
    

    CommunityUpdatePersons(PersonDirectory persondirectory) {
        initComponents();
        this.persondirectory=persondirectory;
        populateTable();
        
        
        //String today;
        //today = formatter.format(new Date());
        //Date maxdate = new Date();
        Date maxdate = new Date();
        try
            {
        String smalldate = "01-01-0001 00:00:00";
        for(Person person: persondirectory.getPersonHistory()){
            
                Date thisDate =new SimpleDateFormat(("MM-dd-yyyy HH:mm:ss")).parse(person.getUpdateDate());
                maxdate = new SimpleDateFormat(("MM-dd-yyyy HH:mm:ss")).parse(smalldate);
                
                if (thisDate.compareTo(maxdate)>0)
                    maxdate=thisDate;
            }
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
        txtMostRecentUpdate.setText(formatter.format(maxdate));
        
          
        } catch (ParseException e) {
            e.printStackTrace();
        }
            
        
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMostRecentUpdate = new javax.swing.JTextField();
        lblCarSerNum1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCarNumPlate1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblModel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblYearofManuf1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersons = new javax.swing.JTable();
        lblCarSerNum2 = new javax.swing.JLabel();
        txtFindPerson = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel2.setBackground(new java.awt.Color(62, 193, 211));

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Person Data");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Last Updated On : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMostRecentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtMostRecentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblCarSerNum1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarSerNum1.setForeground(new java.awt.Color(0, 102, 102));
        lblCarSerNum1.setText("Name  :");

        txtName.setBackground(new java.awt.Color(204, 204, 204));

        lblCarNumPlate1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarNumPlate1.setForeground(new java.awt.Color(0, 102, 102));
        lblCarNumPlate1.setText("Age     :");

        txtAge.setBackground(new java.awt.Color(204, 204, 204));

        lblModel1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblModel1.setForeground(new java.awt.Color(0, 102, 102));
        lblModel1.setText("Address :");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));

        lblYearofManuf1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblYearofManuf1.setForeground(new java.awt.Color(0, 102, 102));
        lblYearofManuf1.setText("Community :");

        lblCity1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCity1.setForeground(new java.awt.Color(0, 102, 102));
        lblCity1.setText("City :");

        txtCommunity.setBackground(new java.awt.Color(204, 204, 204));

        txtCity.setBackground(new java.awt.Color(204, 204, 204));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 178, 202));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 178, 202));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 178, 202));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblPersons.setForeground(new java.awt.Color(0, 102, 102));
        tblPersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(tblPersons);

        lblCarSerNum2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarSerNum2.setForeground(new java.awt.Color(0, 102, 102));
        lblCarSerNum2.setText("Search by Name                   :");

        txtFindPerson.setBackground(new java.awt.Color(204, 204, 204));

        btnFind.setBackground(new java.awt.Color(255, 255, 255));
        btnFind.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        btnFind.setForeground(new java.awt.Color(0, 178, 202));
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblCarSerNum2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFindPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarSerNum1)
                            .addComponent(lblCarNumPlate1)
                            .addComponent(lblModel1))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge)
                            .addComponent(txtName)
                            .addComponent(txtAddress)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYearofManuf1)
                            .addComponent(lblCity1))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCommunity)
                            .addComponent(txtCity))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnView});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerNum2)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerNum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarNumPlate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearofManuf1)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnView});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtAge.setText("");
        txtAddress.setText("");
        txtCommunity.setText("");
        txtCity.setText("");

        String FindName = txtFindPerson.getText();
        int found=0;
        txtFindPerson.setText("");
        for(Person person : this.persondirectory.getPersonHistory())
        {
            if(FindName.trim().equals(person.getName().trim()))
            {
                txtName.setText(person.getName());
                txtAge.setText(String.valueOf(person.getAge()));
                txtAddress.setText(person.getAddress());
                txtCommunity.setText(person.getCommunity());              
                txtCity.setText(person.getCity());
                found=1;
                System.out.print(person.getName()+" Search success!");
            }
        }
        if(found==0)
        {
            JOptionPane.showMessageDialog(this,"No Person found with the given name! Try again!");
            return;
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tblPersons.getSelectedRow();

        if(SelectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPersons.getModel();
        Person selectedPerson = (Person) model.getValueAt(SelectedRowIndex,0);

        int failsafe=0;
        for (Person personiterator : persondirectory.getPersonHistory())
        {
            if( (personiterator.getName().equals(txtName.getText().isEmpty()?"":txtName.getText())) && (!personiterator.getName().equals(selectedPerson.getName())))
            {
                JOptionPane.showMessageDialog(this, "Name must be unique!");
                failsafe=1;
            }

        }
        if(txtName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Name must not be Empty!");
            failsafe=1;
        }

        if(txtCity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "City must not be Empty!");
            failsafe=1;
        }
        if(txtAddress.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Address must not be Empty!");
            failsafe=1;
        }


        if(txtAge.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Age must not be Empty!");
            failsafe=1;
        }
        
                if(txtCommunity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Age must not be Empty!");
            failsafe=1;
        }

        if(txtAddress.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Age must not be Empty!");
            failsafe=1;
        }

        if(failsafe==0)
        {
            selectedPerson.setName(txtName.getText());
            selectedPerson.setCity(txtCity.getText());
            selectedPerson.setCommunity(txtCommunity.getText());
            selectedPerson.setAge(Integer.valueOf(txtAge.getText()));
            selectedPerson.setAddress(txtAddress.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
            selectedPerson.setUpdateDate(formatter.format(new Date()));
            JOptionPane.showMessageDialog(this, "Details updated successfully!");
        }
        populateTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tblPersons.getSelectedRow();

        if(SelectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPersons.getModel();
        Person selectedPerson = (Person) model.getValueAt(SelectedRowIndex,0);

        txtName.setText(selectedPerson.getName());
        txtAge.setText(String.valueOf(selectedPerson.getAge()));
        txtAddress.setText(selectedPerson.getAddress());
        txtCommunity.setText(selectedPerson.getCommunity());              
        txtCity.setText(selectedPerson.getCity());

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tblPersons.getSelectedRow();

        if(SelectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblPersons.getModel();
        Person selectedPerson = (Person) model.getValueAt(SelectedRowIndex,0);

        persondirectory.deletePerson(selectedPerson);
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarNumPlate1;
    private javax.swing.JLabel lblCarSerNum1;
    private javax.swing.JLabel lblCarSerNum2;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblYearofManuf1;
    private javax.swing.JTable tblPersons;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFindPerson;
    private javax.swing.JTextField txtMostRecentUpdate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblPersons.getModel();
        dtm.setRowCount(0);
        
    
        for(Person person: this.persondirectory.getPersonHistory()){
            Object[] row = new Object[5];
            row[0] = person;
            row[1]= Integer.valueOf(person.getAge());
            row[2]= person.getAddress();
            row[3]= person.getCommunity();
            row[4]= person.getCity();
            
            dtm.addRow(row);
   }
    }
}
