/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.Person;
import model.VitalSign;
import model.PersonDirectory;

/**
 *
 * @author shshyam
 */
public class PatientsAddPane extends javax.swing.JPanel {
PersonDirectory persondirectory;
    /**
     * Creates new form AddPatient
     */
    public PatientsAddPane(PersonDirectory persondirectory) {
        initComponents();
        this.persondirectory=persondirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarSerNum1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCarNumPlate1 = new javax.swing.JLabel();
        txtHospital = new javax.swing.JTextField();
        lblModel1 = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JTextField();
        lblYearofManuf1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        txtRespRate = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        btnSamplePatients = new javax.swing.JButton();
        lblCity2 = new javax.swing.JLabel();
        lblYearofManuf2 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCarSerNum2 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));

        lblCarSerNum1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarSerNum1.setForeground(new java.awt.Color(0, 102, 102));
        lblCarSerNum1.setText("Name  :");

        txtName.setBackground(new java.awt.Color(204, 204, 204));

        lblCarNumPlate1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarNumPlate1.setForeground(new java.awt.Color(0, 102, 102));
        lblCarNumPlate1.setText("Preferred Hospital :");

        txtHospital.setBackground(new java.awt.Color(204, 204, 204));

        lblModel1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblModel1.setForeground(new java.awt.Color(0, 102, 102));
        lblModel1.setText("Preferred Doctor :");

        txtDoctor.setBackground(new java.awt.Color(204, 204, 204));

        lblYearofManuf1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblYearofManuf1.setForeground(new java.awt.Color(0, 102, 102));
        lblYearofManuf1.setText("Respiratory Rate :");

        lblCity1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCity1.setForeground(new java.awt.Color(0, 102, 102));
        lblCity1.setText("Heart Rate :");

        txtRespRate.setBackground(new java.awt.Color(204, 204, 204));

        txtHeartRate.setBackground(new java.awt.Color(204, 204, 204));

        btnSamplePatients.setBackground(new java.awt.Color(255, 255, 255));
        btnSamplePatients.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnSamplePatients.setForeground(new java.awt.Color(0, 178, 202));
        btnSamplePatients.setText("Add Sample Patients");
        btnSamplePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamplePatientsActionPerformed(evt);
            }
        });

        lblCity2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCity2.setForeground(new java.awt.Color(0, 102, 102));
        lblCity2.setText("Temperature :");

        lblYearofManuf2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblYearofManuf2.setForeground(new java.awt.Color(0, 102, 102));
        lblYearofManuf2.setText("Blood Pressure :");

        txtTemp.setBackground(new java.awt.Color(204, 204, 204));

        txtBP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 178, 202));
        jLabel1.setText("Add Vital Signs below :");

        lblCarSerNum2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        lblCarSerNum2.setForeground(new java.awt.Color(0, 102, 102));
        lblCarSerNum2.setText("Patient ID  :");

        txtPatientID.setBackground(new java.awt.Color(204, 204, 204));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 178, 202));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Optima", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 144, 161));
        jLabel3.setText("Please enter a patient entry only if the person details exist in Community data. If not, please create a person profile first.");

        jPanel2.setBackground(new java.awt.Color(62, 193, 211));

        jLabel2.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Patient details below ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel2)
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCarNumPlate1)
                                .addComponent(lblModel1)
                                .addComponent(lblCarSerNum2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblYearofManuf1)
                                            .addComponent(lblCity1)
                                            .addComponent(lblCarSerNum1))
                                        .addGap(102, 102, 102)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRespRate)
                                            .addComponent(txtHeartRate)
                                            .addComponent(txtPatientID)
                                            .addComponent(txtName)
                                            .addComponent(txtHospital)
                                            .addComponent(txtDoctor)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblYearofManuf2)
                                            .addComponent(lblCity2))
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSamplePatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(303, 303, 303)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerNum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSerNum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarNumPlate1)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel1))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearofManuf1)
                    .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearofManuf2)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity2)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSamplePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSamplePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamplePatientsActionPerformed
        // TODO add your handling code here:
         File file = new File("src/Resources/PatientData.txt");

         try {
            Scanner sc = new Scanner(file);
          //   SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
            while (sc.hasNextLine()) {
                String readLine = sc.nextLine();
                String[] lineArray = readLine.split(",");
                Patient patient =  new Patient();
                patient.setPatientID(lineArray[1].trim());
                patient.setDoctorName(lineArray[3].trim());
                patient.setPreferredHospital(lineArray[2].trim());
                String Name=lineArray[0].trim();
                for (Person personiterator : this.persondirectory.getPersonHistory())
                {
                    if( Name.equals(personiterator.getName().isEmpty()?"":personiterator.getName()))
                        {
                            personiterator.setPatient(patient);
                            
                        } 
                }
               
            }

        JOptionPane.showMessageDialog(this, "Sample Data Added successfully!");
            
            sc.close();
         } catch(Exception e) {
             e.printStackTrace();
         }
     
    }//GEN-LAST:event_btnSamplePatientsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
          Person selectedPerson = new Person();
       Patient patient = new Patient();
       VitalSign vitalSign = patient.getVitalSignHistory().createAndAddVitalSign();
       
        if(txtName.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Name must not be Empty!");
               return;
         }
        
       int personexists=0;
         for (Person personiterator : this.persondirectory.getPersonHistory())
        {
           if( personiterator.getName().equals(txtName.getText().isEmpty()?"":txtName.getText()))
           {
               
               personexists=1;
           } 
        }
         
         if(personexists==0)
             JOptionPane.showMessageDialog(this, "Person details do not exist! Please create person details in community pane first!");
        else
         {
          for (Person personiterator : this.persondirectory.getPersonHistory())
             {
                 if( personiterator.getName().equals(txtName.getText().isEmpty()?"":txtName.getText()))
                     selectedPerson=personiterator;
             }
          
          
         
        int failsafe=0;
        if(txtPatientID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Patient ID must not be Empty!");
            failsafe=1;
        }
        if(txtHospital.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Hospital name must not be Empty!");
            failsafe=1;
        }
        
        if(txtDoctor.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Doctor name must not be Empty!");
            failsafe=1;
        }

        
        if(txtHeartRate.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "HeartRate must not be Empty!");
            failsafe=1;
        }
        if(txtRespRate.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Respiration rate must not be Empty!");
            failsafe=1;
        }

        if(txtBP.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "BP must not be Empty!");
            failsafe=1;
        }
        
        if(txtTemp.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Temperature must not be Empty!");
            failsafe=1;
        }

        if(failsafe==0)
        {
            
            patient.setPatientID(txtPatientID.getText());
            patient.setDoctorName(txtDoctor.getText());
            patient.setPreferredHospital(txtDoctor.getText());
            
            
            vitalSign.setRespiratoryRate(Integer.valueOf(txtRespRate.getText()));
            vitalSign.setHeartRate(Integer.valueOf(txtHeartRate.getText()));
            vitalSign.setBloodPressure(Integer.valueOf(txtBP.getText()));
            vitalSign.setTemperature(Float.valueOf(txtTemp.getText()));
            /*Set current date and time as TimeStamp*/
            vitalSign.setTimestamp(new Date());
            selectedPerson.setPatient(patient);
            
            JOptionPane.showMessageDialog(this, "Details updated successfully!");
        }
         }
      
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSamplePatients;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCarNumPlate1;
    private javax.swing.JLabel lblCarSerNum1;
    private javax.swing.JLabel lblCarSerNum2;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblYearofManuf1;
    private javax.swing.JLabel lblYearofManuf2;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtRespRate;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
